apiVersion: v1
kind: Secret
metadata:
  name: litellm-prometheus-metrics-secret
  namespace: monitoring
type: Opaque
stringData:
  LITELLM_MASTER_KEY: "sk-1234"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: "sk-1234"
