apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - 00-namespace.yaml
  - 02-grafana.yaml
  - 05-prometheus.yaml
  - 08-prometheus-oauth2-proxy.yaml
  - 09-prometheus-auth-ingress.yaml
  - 10-network-policies.yaml

configMapGenerator:
  - name: grafana-config
    files:
      - grafana-config/grafana.ini

  - name: grafana-datasources
    files:
      - prometheus.yaml=grafana-config/prometheus-datasource.yaml

  - name: prometheus-oauth2-proxy-config
    files:
      - oauth2-proxy.cfg=oauth2-proxy/oauth2-proxy.cfg