apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-ca
  namespace: external-secrets
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBozCCAUmgAwIBAgIQZrjtCIw1SxVgjBxbGiwk8DAKBggqhkjOPQQDAjAwMS4w
    LAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDI2IEVDQyBSb290MB4X
    DTI2MDcyMDA5MjYwN1oXDTM2MDUyODA5MjYwN1owMDEuMCwGA1UEAxMlQ2FkZHkg
    TG9jYWwgQXV0aG9yaXR5IC0gMjAyNiBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABDXgdQvK1Mgsj/yWlEMUiM589KIYXNrUQsXpcFt0C04iy7a2hnj4
    8XSkRRbTvO6w75ZMrrQWsNKzTUPi61Q3A62jRTBDMA4GA1UdDwEB/wQEAwIBBjAS
    BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBSvycX9iRk0+7duZhR8OAxc2CMC
    xDAKBggqhkjOPQQDAgNIADBFAiEAqxMiRNuPbYNuLKjDYxNtDNCBURk3R2QQ3M93
    MGL3jtMCIFBA4KktErXEZzUKA8AeJdfly3YZ360a9WchgpCjJSB6
    -----END CERTIFICATE-----