apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: lab-wildcard-tls
spec:
  externalSecretName: lab-wildcard-tls
  namespaceSelectors:
    - matchLabels:
        homelab-tls: lab-wildcard
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: infisical
      kind: ClusterSecretStore
    target:
      name: lab-wildcard-tls
      creationPolicy: Owner
      template:
        type: kubernetes.io/tls
    data:
      - secretKey: tls.crt
        remoteRef:
          key: /tls/LAB_WILDCARD_CRT
      - secretKey: tls.key
        remoteRef:
          key: /tls/LAB_WILDCARD_KEY

# Selectivelly apply the secret for the following apps by labels
# kubectl label namespace \
#   argocd longhorn-system litellm normal-ass-note pi-dashboard postgres \
#   homelab-tls=lab-wildcard --overwrite