apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-infisical-ca.yaml
  # - 02-infisical-universal-auth.yaml --->>> mannually run this
  - 03-infisical-cluster-secret-store.yaml