apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.2
      helm:
        releaseName: longhorn
        values: |
          # Label only worker nodes longhorn-enabled=true before syncing.
          global:
            nodeSelector:
              longhorn-enabled: "true"

          # Two eligible workers are required for both CSI replicas to run.
          csi:
            podAntiAffinityPreset: hard
            attacherReplicaCount: 2
            provisionerReplicaCount: 2
            resizerReplicaCount: 2
            snapshotterReplicaCount: 2

          longhornUI:
            replicas: 2
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app: longhorn-ui
                    topologyKey: kubernetes.io/hostname

          persistence:
            defaultClass: true            # local-path is default, mark this will make longhorn default StorageClass
            defaultClassReplicaCount: 2
            reclaimPolicy: Retain         # Delete PVC ->  PV remains Released -> data still exists -> manually recover or delete later

          defaultSettings:
            # Covers instance managers, CSI components, and engine images.
            systemManagedComponentsNodeSelector: "longhorn-enabled:true"
            storageOverProvisioningPercentage: 100
            defaultDataPath: /var/lib/longhorn
            
            nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod     # Pod Deletion Policy When Node is Down
            autoDeletePodWhenVolumeDetachedUnexpectedly: true                         # Automatically Delete Workload Pod when Volume Is Detached Unexpectedly
            
            orphanResourceAutoDeletion: "replica-data;instance"            # automatically clean orphaned engine/replica runtime instances
            orphanResourceAutoDeletionGracePeriod: 600                     # after this configured grace period.

          preUpgradeChecker:
            jobEnabled: false

    - repoURL: https://github.com/Quangsumi/k3s-homelab.git
      targetRevision: main
      path: infrastructure/longhorn   

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true