apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litellm
type: Opaque
stringData:
  # Must start with sk-. This is the admin/master key for LiteLLM.
  LITELLM_MASTER_KEY: "sk-1234"

  # Generate a long random value and do not change it after LiteLLM stores model keys in DB.
  LITELLM_SALT_KEY: "CHANGE_ME_LONG_RANDOM_SALT_KEY_DO_NOT_CHANGE_LATER"

  # DATABASE_URL: "postgresql://litellm:dbpassword9090@postgres:5432/litellm"   # postgres on same namespace
  DATABASE_URL: "postgresql://quangsumi:dbpassword9090@postgres.postgres.svc.cluster.local:5432/litellm" # postgress on diff namespace