apiVersion: v1
kind: Service
metadata:
  name: traefik-tailscale-ha
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    tailscale.com/hostname: homelab-traefik-ha
    tailscale.com/proxy-group: traefik-ingress-proxies
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: websecure
      protocol: TCP
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP