apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
stringData:
  POSTGRES_USER: quangsumi
  POSTGRES_PASSWORD: "dbpassword9090"
  POSTGRES_DB: postgres # default db

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: postgres
type: Opaque
stringData:
  DATA_SOURCE_LITELLM: "postgresql://quangsumi:dbpassword9090@postgres:5432/litellm?sslmode=disable"