apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
stringData:
  POSTGRES_USER: litellm
  POSTGRES_PASSWORD: "dbpassword9090"
  POSTGRES_DB: litellm

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: postgres
type: Opaque
stringData:
  # This must match the Postgres secret above.
  DATA_SOURCE_NAME: "postgresql://litellm:dbpassword9090@postgres:5432/litellm?sslmode=disable"