apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret-infisical
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: /postgres/PGADMIN_DEFAULT_EMAIL
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: /postgres/PGADMIN_DEFAULT_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-oidc
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: pgadmin-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: /postgres/PGADMIN_OIDC_CLIENT_SECRET