apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-ca-key-pair
  namespace: cert-manager
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h

  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore

  target:
    name: homelab-ca-key-pair
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls

  data:
    - secretKey: tls.crt
      remoteRef:
        key: /tls/HOMELAB_ROOT_CA_CRT

    - secretKey: tls.key
      remoteRef:
        key: /tls/HOMELAB_ROOT_CA_KEY