apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: caddy-trust-bundle
spec:
  sources:
    - useDefaultCAs: true       # Public Internet CAs, Mozilla/public CA bundle from Let's Encrypt, Cloudflare, etc.
    - configMap:
        name: caddy-root-ca
        key: ca.crt
  target:
    configMap:
      key: ca-bundle.pem        # include caddy-root-ca and default CAs in the ca-bundle.pem file
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - argocd
            - external-secrets
            - postgres
            - monitoring