apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-external-secret.yaml
  - 05-cluster-issuer.yaml
  - 10-caddy-trust-bundle.yaml

# let kustomize create the ConfigMap from the .crt file,
# instead of manually creating the ConfigMap and put the .crt conent in the ConfigMap
configMapGenerator:
  - name: caddy-root-ca
    files:
      - ca.crt=caddy-root-ca.crt

generatorOptions:
  disableNameSuffixHash: true # eg: caddy-root-ca-6dm7b6tk5g, new change new hash. Disable in this case and let trust-manager handle this.