apiVersion: v1
kind: Service
metadata:
  name: argocd-lb
  namespace: argocd
  labels:
    app: argocd
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.63.203
  selector:
    app: argocd-server
  ports:
    - port: 80
      targetPort: http