apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: litellm-stack
type: Opaque
stringData:
  POSTGRES_USER: litellm
  POSTGRES_PASSWORD: "dbpassword9090"
  POSTGRES_DB: litellm
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: litellm-stack
type: Opaque
stringData:
  # Must start with sk-. This is the admin/master key for LiteLLM.
  LITELLM_MASTER_KEY: "sk-1234"

  # Generate a long random value and do not change it after LiteLLM stores model keys in DB.
  LITELLM_SALT_KEY: "CHANGE_ME_LONG_RANDOM_SALT_KEY_DO_NOT_CHANGE_LATER"

  # This must match the Postgres secret above.
  DATABASE_URL: "postgresql://litellm:dbpassword9090@postgres:5432/litellm"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: litellm-stack
type: Opaque
stringData:
  # This must match the Postgres secret above.
  DATA_SOURCE_NAME: "postgresql://litellm:dbpassword9090@postgres:5432/litellm?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: litellm-stack
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: "sk-1234"
